version: '3.3'
services:
  node:
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    command: ["/wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
    ports:
      - "8080:4000"
    volumes:
      - type: bind
        source: ./
        target: /graphql-server-example
    networks:
      - my-app
    depends_on:
      - "mongo"
  mongo:
    build:
      context: .
      dockerfile: .docker/mongo.dockerfile
    ports:
      - "3000:27017"
    volumes:
      - "/data/mongodb:/data/db"
    networks:
      - my-app

networks:
  my-app: